### ISSUE TITLE
No Badges

### ISSUE THREAD

**Issue by aauyong** [Akashortstack/PsychoRando#1]
Had an issue where I wasn't getting any badges. Initially, I wasn't getting any rewards from ranking up in the sanctuary, but didn't think it was a big deal. But I got clairvoyance in Milkman Conspiracy fridge, and yet it wasn't added to my inventory

**Comment by Akashortstack** [comment]
Were other collectibles all randomizing correctly? Clairvoyance in Milkman fridge is weirdly a vanilla location, but all original collectibles should be deleted and replaced by the mod. If there is some way to post or attach the seed you had this issue with that would help too

**Comment by aauyong** [comment]
Well turns out this one is on me. While trying to convert the RandoSeed file, I realized I had copy pasted the online seed rather than the randomized one. In hindsight, cards and souvenirs were in vanilla locations, so I should've realized

**Comment by Akashortstack** [comment]
v0.4 coming out soon will prevent any copy paste issues, because it's now a python script :)
